---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-operator-reinstall-sa
  namespace: openshift-managed-upgrade-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sre-operator-reinstall-role
  namespace: openshift-managed-upgrade-operator
rules:
- apiGroups:
  - "operators.coreos.com"
  resources:
  - clusterserviceversions
  - subscriptions
  - installplans
  verbs:
  - list
  - get
  - delete
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-operator-reinstall-rb
  namespace: openshift-managed-upgrade-operator
roleRef:
  kind: Role
  name: sre-operator-reinstall-role
  apiGroup: rbac.authorization.k8s.io
  namespace: openshift-managed-upgrade-operator
subjects:
- kind: ServiceAccount
  name: sre-operator-reinstall-sa
  namespace: openshift-managed-upgrade-operator